haskell-effectful/effectful

- src/Effectful/Internal/Monad.hs
- `Monoid`
- `PrimMonad`
- `Semigroup`
> Added some more instances for Eff

- effectful/effectful.cabal
- effectful/src/Effectful/Environment.hs
- effectful/tests/EnvironmentTests.hs
- effectful/tests/Main.hs
- effectful/tests/Utils.hs
As proposed in https://github.com/arybczak/effectful/issues/23#issuecomment-877714896.
> Add Environment effect

- effectful/effectful.cabal
- effectful/src/Effectful/Timeout.hs
- effectful/tests/Main.hs
- effectful/tests/TimeoutTests.hs
This PR adds a `Timeout` effect based on [`System.Timeout`](https://hackage.haskell.org/package/base-4.15.0.0/docs/System-Timeout.html).
> Add Timeout effect

- effectful/effectful.cabal
- effectful/src/Effectful/FileSystem.hs
This PR adds a `FileSystem` effect to the `effectful` package as proposed in https://github.com/arybczak/effectful/issues/23#issuecomment-877714896.
> Add FileSystem effect

- .github/workflows/haskell-ci.yml
- doctest.sh
- effectful-core/src/Effectful.hs
- effectful-core/src/Effectful/Dispatch/Dynamic.hs
- effectful-core/src/Effectful/Dispatch/Static.hs
- effectful-core/src/Effectful/Error.hs
- effectful-core/src/Effectful/Error/Dynamic.hs
- effectful-core/src/Effectful/Internal/Env.hs
- effectful-core/src/Effectful/Internal/Monad.hs
- effectful-core/src/Effectful/Monad.hs
- effectful-core/src/Effectful/Reader.hs
- effectful-core/src/Effectful/Reader/Dynamic.hs
- effectful-core/src/Effectful/State/Dynamic.hs
- effectful-core/src/Effectful/State/Local.hs
- effectful-core/src/Effectful/State/Shared.hs
- effectful-core/src/Effectful/Writer/Dynamic.hs
- effectful-core/src/Effectful/Writer/Local.hs
- effectful-core/src/Effectful/Writer/Shared.hs
- effectful/bench/Concurrency.hs
- effectful/bench/FileSizes.hs
- effectful/examples/FileSystem.hs
- effectful/src/Effectful/Concurrent/Effect.hs
- effectful/src/Effectful/Environment.hs
- effectful/src/Effectful/FileSystem/Effect.hs
- effectful/src/Effectful/Process.hs
- effectful/src/Effectful/Resource.hs
- effectful/src/Effectful/Temporary.hs
- effectful/src/Effectful/Timeout.hs
- effectful/tests/ErrorTests.hs
- effectful/tests/StateTests.hs
Minimal proof of concept based on https://github.com/arybczak/effectful/pull/48#discussion_r779510451.
@ilyakooo0 thoughts?
> Prevent possibility of mixing functions for different dispatch types

- .github/workflows/haskell-ci.yml
- README.md
- cabal.haskell-ci
- cabal.project
- effectful-plugin/CHANGELOG.md
- effectful-plugin/LICENSE
- effectful-plugin/README.md
- effectful-plugin/effectful-plugin.cabal
- effectful-plugin/src/Effectful/Plugin.hs
- effectful-plugin/src/Effectful/Plugin/Internal.hs
- effectful-plugin/tests/PluginTests.hs
Fixes https://github.com/haskell-effectful/effectful/issues/54.
> Port the plugin from cleff

- effectful-core/src/Effectful/Reader/Dynamic.hs
- effectful-core/src/Effectful/Reader/Static.hs
Fixes https://github.com/haskell-effectful/effectful/issues/9.
> Add withReader

- effectful-core/CHANGELOG.md
- effectful-core/effectful-core.cabal
- effectful-core/src/Effectful/Internal/Monad.hs
- effectful-plugin/effectful-plugin.cabal
- effectful-th/effectful-th.cabal
- effectful/effectful.cabal
- effectful/tests/UnliftTests.hs
Fixes https://github.com/haskell-effectful/effectful/issues/69.
> Don't reset the strategy inside the continuation in withEffToIO

- effectful-core/CHANGELOG.md
- effectful-core/effectful-core.cabal
- effectful-core/src/Effectful/Internal/Monad.hs
- effectful-core/src/Effectful/Prim.hs
- effectful/CHANGELOG.md
- effectful/effectful.cabal
- effectful/tests/Main.hs
- effectful/tests/PrimTests.hs
A bit more elaborate version of #94.
> Change PrimState for Eff from RealWorld to PrimStateEff

- README.md
- effectful-core/CHANGELOG.md
- effectful-core/effectful-core.cabal
- effectful-core/src/Effectful/Dispatch/Static/Primitive.hs
- effectful-core/src/Effectful/Internal/Env.hs
- effectful-core/src/Effectful/Internal/Monad.hs
- effectful-core/src/Effectful/NonDet.hs
- effectful/CHANGELOG.md
- effectful/effectful.cabal
- effectful/tests/EnvTests.hs
- effectful/tests/Main.hs
- effectful/tests/NonDetTests.hs
Improves upon and supersedes #100.
@mmhat thoughts?
FYI, tests need slight adjustments and I'm not sure about the naming of `runNonDetTrans`.
> Add the NonDet effect

- effectful-core/CHANGELOG.md
- effectful-core/effectful-core.cabal
- effectful-core/src/Effectful/Dispatch/Dynamic.hs
- effectful/CHANGELOG.md
- effectful/effectful.cabal
Improves performance for use cases like #108.
> Add localSeqLift and localLift

- effectful-core/src/Effectful.hs
- effectful-core/src/Effectful/Internal/Monad.hs
address issue https://github.com/haskell-effectful/effectful/issues/112
> Add withSeqEffToIO and withConcEffToIO functions

- effectful-core/src/Effectful/Internal/Env.hs
> Don't put thunks with toAny into the Env

- effectful-core/CHANGELOG.md
- effectful-core/src/Effectful/Dispatch/Dynamic.hs
- effectful-core/src/Effectful/Internal/Effect.hs
- effectful-core/src/Effectful/Internal/Env.hs
- effectful-core/src/Effectful/Internal/Monad.hs
- effectful/CHANGELOG.md
- effectful/tests/EnvTests.hs
> Make inject work with effect stacks sharing a polymorphic suffix

- effectful-core/CHANGELOG.md
- effectful-core/src/Effectful/Error/Dynamic.hs
- effectful-core/src/Effectful/Error/Static.hs
- effectful/CHANGELOG.md
> Add runErrorWith and runErrorNoCallStackWith

- effectful-core/CHANGELOG.md
- effectful-core/effectful-core.cabal
- effectful-core/src/Effectful/Labeled.hs
- effectful/CHANGELOG.md
- effectful/bench/Countdown.hs
- effectful/bench/Main.hs
- effectful/effectful.cabal
Proof of concept for support of having multiple effects of the same type in scope.
> Add support for labeled effects

- effectful-core/src/Effectful/Internal/Utils.hs
Making use of https://github.com/haskell/core-libraries-committee/issues/117
> Use `fromThreadId` on GHC >=9.8

- effectful-core/CHANGELOG.md
- effectful-core/effectful-core.cabal
- effectful-core/src/Effectful/Internal/Effect.hs
- effectful-core/src/Effectful/Provider.hs
- effectful-core/src/Effectful/Provider/List.hs
- effectful/CHANGELOG.md
- effectful/effectful.cabal
Proof or concept for generalization of `Provider` that allows handling multiple effects.
Useful in niche situations. I didn't generalize the original provider because types can be confusing as it is.
> Add Effectful.Provider.List

- README.md
- effectful-core/src/Effectful.hs
- effectful-core/src/Effectful/Dispatch/Static.hs
> Encourage dynamic dispatch as a default

- effectful-core/src/Effectful/Dispatch/Dynamic.hs
- effectful/tests/EnvTests.hs
Fixes https://github.com/haskell-effectful/effectful/issues/239.
> Fix copyRefs in Effect.Dispatch.Dynamic

- effectful-core/CHANGELOG.md
- effectful-core/effectful-core.cabal
- effectful-core/src/Effectful/Exception.hs
- effectful-core/src/Effectful/State/Static/Local.hs
- effectful-core/src/Effectful/State/Static/Shared.hs
- effectful/CHANGELOG.md
> Base Effectful.Exception on Control.Exception

- effectful-core/src/Effectful/Internal/Monad.hs
Use the other solution from https://gitlab.haskell.org/ghc/ghc/-/issues/20008, Core doesn't seem to have any relevant changes.
> Make Monad instance canonical

- effectful-core/src/Effectful/Reader/Dynamic.hs
- effectful/tests/ReaderTests.hs
Turns out it's faster than going through a static one.
> Use purely dynamic Reader
