effectful/effectful.cabal
effectful/src/Effectful/Process.hs

This PR adds a `Process` effect used to call run child processes. Note that instead of building upon the [process](https://hackage.haskell.org/package/process) library it uses [typed-process](https://hackage.haskell.org/package/typed-process) in order to provide more type safety.
The idea for this effect came from [this](https://github.com/arybczak/effectful/issues/23#issuecomment-877714896) discussion.

Added Process effect

---

effectful/bench/Concurrency.hs
effectful/bench/Unlift.hs
effectful/effectful.cabal
effectful/src/Effectful/Concurrent.hs
effectful/src/Effectful/Concurrent/Async.hs
effectful/src/Effectful/Concurrent/Base.hs
effectful/src/Effectful/Concurrent/Internal.hs
effectful/tests/AsyncTests.hs
effectful/tests/EnvironmentTests.hs

This PR replaces the `AsyncE` effect with an effect named `Concurrent`.
The code of the former `AsyncE` effect is now located in the `Effectful.Concurrent.Async` module.
In addition to that we add a new module `Effectful.Concurrent.Base` which contains the concurrency primitives found in the `Control.Concurrent` module of the `base` package.
Both `Effectful.Concurrent.Async` and `Effectful.Concurrent.Base` are part of the `Concurrent` effect which lives in an internal module `Effectful.Concurrent.Internal` and gets re-exported by the two modules.

Concurrent effect

---

.github/workflows/haskell-ci.yml
cabal.project
doctest.sh
effectful-th/CHANGELOG.md
effectful-th/LICENSE
effectful-th/effectful-th.cabal
effectful-th/src/Effectful/TH.hs
effectful-th/tests/ThTests.hs

Supersedes #56, based on the code from `cleff` and #56.
Doesn't need `TemplateHaskell`, works with more data types and produces arguably prettier type signatures.

Add effectful-th

---

effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful/Dispatch/Dynamic.hs
effectful-plugin/effectful-plugin.cabal
effectful-th/effectful-th.cabal
effectful/CHANGELOG.md
effectful/effectful.cabal

This both relaxes former advertised behavior of `SuffixOf` as well as makes it behave properly as the type family version didn't.

Change SuffixOf to SharedSuffix and make it behave as advertised

---

effectful-core/CHANGELOG.md
effectful-core/src/Effectful.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful/CHANGELOG.md

Turns out this is sometimes needed when you (re)interpret higher order effects.

Add raiseWith

---

effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful/Dispatch/Dynamic.hs
effectful-core/src/Effectful/Dispatch/Static/Primitive.hs
effectful-core/src/Effectful/Error/Static.hs
effectful-core/src/Effectful/Internal/Env.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-plugin/effectful-plugin.cabal
effectful-th/effectful-th.cabal
effectful/CHANGELOG.md
effectful/effectful.cabal
effectful/tests/EnvTests.hs

It shuffles time complexities for `Env` operations around, but overall:
- It speeds things up because of less indirections.
- It makes the API simpler since there is no longer need to fork.

Make storage references in the environment immutable

---

effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-core/src/Effectful/Internal/Unlift.hs
effectful/CHANGELOG.md
effectful/effectful.cabal
effectful/tests/ConcurrencyTests.hs
effectful/tests/UnliftTests.hs
effectful/tests/Utils.hs

I've been slightly dissatisfied with discrepancy between `withEffToIO` and local unlifting functions from `Effectful.Dispatch.Dynamic`, even more so since #113.
I've also noticed that unlifting strategies can confuse people and the fact that `withRunInIO` and `withEffToIO` implicitly take its strategy from the `IOE` context doesn't help.
`withRunInIO` can't be fixed as it comes from `MonadUnliftIO`, but `withEffToIO` can. Sadly it's a (minor) breaking change, but should be worth it in the long run.

Make withEffToIO explicitly take an unlifting strategy

---

effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful/Reified.hs
effectful/CHANGELOG.md
effectful/effectful.cabal
effectful/tests/EnvTests.hs

Fixes #134.
@googleson78 does that work for you?
FWIW if it ends up getting merged, I'll probably rename it to something else, because it's really about turning an interpreter into an effect, so `Scoped` is a bit weird name for this. EDIT: though I'm not sure what the more appropriate name would be.
Provided `runScoped` should be enough for all use cases. Runners in `polysemy` have insane types and I don't know what are the differences between them, but `runScopedNew` supposedly subsumes them and IIUC my `runScoped` is a more readable version of it.
~~Also, looks like it might be somewhat annoying to use without the plugin if you make use of an effect with parameters.~~ Nah, the current order of type parameters makes it alright.

Add support for turning an effect handler into an effectul operation

---

effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful.hs
effectful-core/src/Effectful/Dispatch/Dynamic.hs
effectful-core/src/Effectful/Internal/Env.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-core/src/Effectful/Internal/Unlift.hs
effectful/CHANGELOG.md
effectful/tests/UnliftTests.hs

Turns out that lifting functions that e.g. employ a worker thread to run an unlifted argument is a bit problematic at the moment, because their control flow is observably sequential, but SeqUnlift doesn't work with them.
This bridges the gap.

Add the SyncUnlift strategy

---

doctest.sh
effectful-core/CHANGELOG.md
effectful-core/src/Effectful/Dispatch/Dynamic.hs
effectful/CHANGELOG.md

@ocharles this renames the helper we discussed in #195 and adds one that works in the opposite direction (just fyi).

Rename localHandle to localLend and add localBorrow

---

effectful-th/src/Effectful/TH.hs
effectful-th/tests/ThTests.hs

Fixes #225
I went ahead and put together a PR, since it's very simple.
I can't see a good way to test this, but you can verify by opening the test file in HLS, adding some references to the sending functions, and checking that they have the right haddock in the hover.

Get haddock for makeEffect from the declaration

---

effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful/Dispatch/Dynamic.hs
effectful-core/src/Effectful/Fail.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-core/src/Effectful/Provider.hs
effectful-plugin/tests/PluginTests.hs
effectful/CHANGELOG.md
effectful/bench/FileSizes.hs
effectful/effectful.cabal
effectful/tests/EnvTests.hs
effectful/tests/ErrorTests.hs
effectful/tests/NonDetTests.hs
effectful/tests/StateTests.hs

Supersedes #230.
@michaelpj @ocharles does that work for you?
I decided to go with `handleWith` instead of `interpretWith` since the name `interpretWith` is too close to `interpret` and might be confusing.
Still reads nicely:
```haskell
myFunction arg `handleWith_` \case
NotifyA i -> ...
NotifyB s -> ...
```
and won't clash with `Control.Monad.Catch`.

Utility functions for handling effects

---

effectful-core/CHANGELOG.md
effectful-core/src/Effectful/Error/Dynamic.hs
effectful-core/src/Effectful/Error/Static.hs
effectful-core/src/Effectful/Labeled/Error.hs
effectful-plugin/tests/PluginTests.hs
effectful/CHANGELOG.md

For example, if a third-party library spawns worker threads and if a job throws, it simply catches SomeException, logs it and retries the job later, as of today internal exceptions representing errors of the `Error` effect wouldn't show any info about the error, just the backtrace.
This fixes it at the cost of small API breakage.
TODO changelog

Improve Show instance of Effectful.Error.Static.ErrorWrapper

---

effectful-core/CHANGELOG.md
effectful-core/src/Effectful/Internal/Env.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-core/src/Effectful/Writer/Static/Local.hs
effectful-core/src/Effectful/Writer/Static/Shared.hs
effectful/tests/StateTests.hs

Fixes https://github.com/haskell-effectful/effectful/issues/237.

Consider array reallocations when doing monadic state updates

---

.github/workflows/haskell-ci.yml
effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful/Internal/Env.hs
effectful-core/src/Effectful/Internal/Unlift.hs
effectful-core/src/Effectful/Internal/Utils.hs
effectful-core/src/Effectful/State/Static/Shared.hs
effectful-core/src/Effectful/Writer/Static/Shared.hs
effectful/CHANGELOG.md
effectful/effectful.cabal
effectful/src/Effectful/Concurrent/Chan/Strict.hs
effectful/src/Effectful/Concurrent/MVar/Strict.hs
effectful/src/Effectful/Concurrent/MVar/Strict/Compat.hs
effectful/src/Effectful/Concurrent/STM.hs
effectful/src/Effectful/Prim/IORef.hs
effectful/src/Effectful/Prim/IORef/Strict.hs
effectful/tests/StateTests.hs

Testing, will merge after `strict-mutable-base` is released.

Use strict-mutable-base

---

effectful-core/CHANGELOG.md
effectful-core/src/Effectful/Dispatch/Dynamic.hs
effectful-core/src/Effectful/Error/Dynamic.hs
effectful-core/src/Effectful/Error/Static.hs
effectful-core/src/Effectful/Fail.hs
effectful-core/src/Effectful/Internal/Env.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-core/src/Effectful/Labeled.hs
effectful-core/src/Effectful/Labeled/Error.hs
effectful-core/src/Effectful/Labeled/Reader.hs
effectful-core/src/Effectful/Labeled/State.hs
effectful-core/src/Effectful/Labeled/Writer.hs
effectful-core/src/Effectful/NonDet.hs
effectful-core/src/Effectful/Provider.hs
effectful-core/src/Effectful/Provider/List.hs
effectful-core/src/Effectful/Reader/Dynamic.hs
effectful-core/src/Effectful/Reader/Static.hs
effectful-core/src/Effectful/State/Dynamic.hs
effectful-core/src/Effectful/State/Static/Local.hs
effectful-core/src/Effectful/State/Static/Shared.hs
effectful-core/src/Effectful/Writer/Dynamic.hs
effectful-core/src/Effectful/Writer/Static/Local.hs
effectful-core/src/Effectful/Writer/Static/Shared.hs
effectful-plugin/src-legacy/Effectful/Plugin.hs
effectful-plugin/src/Effectful/Plugin.hs

Bechmarks are pretty much unaffected because most of these functions are small and GHC inlines them.

Add HasCallStack constraints for easier debugging

---

effectful-core/CHANGELOG.md
effectful-core/src/Effectful/Dispatch/Dynamic.hs
effectful-core/src/Effectful/Internal/Env.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-core/src/Effectful/Internal/Unlift.hs
effectful/CHANGELOG.md

Add SeqForkUnlift strategy

---

effectful-core/CHANGELOG.md
effectful-core/src/Effectful/Dispatch/Static/Primitive.hs
effectful-core/src/Effectful/Internal/Env.hs
effectful-core/src/Effectful/Internal/Monad.hs
effectful-core/src/Effectful/NonDet.hs
effectful/CHANGELOG.md
effectful/tests/EnvTests.hs
effectful/tests/StateTests.hs

Fix NonDet/OnEmptyRollback

---

effectful-core/CHANGELOG.md
effectful-core/effectful-core.cabal
effectful-core/src/Effectful/Internal/Monad.hs
effectful/CHANGELOG.md
effectful/effectful.cabal

Change the order of type parameters in raise for better usability

---

effectful-core/CHANGELOG.md
effectful-core/src/Effectful/Exception.hs
effectful/CHANGELOG.md

Fixes #304.
A small wrinkle is that `withException` will also capture `ErrorWrapper`, but I can live with that.

Add withException to Effectful.Exception

---

effectful/bench/Countdown.hs
effectful/bench/FileSizes.hs
effectful/bench/Main.hs

Turns out that running unspecialized code written with mtl style effects in mind via effectful's `Eff` is always faster than running via a transformer stack. Crazy.
`countdown.1000`:
```
mtl (transformers)
shallow:        OK
51.1 μs ± 2.9 μs, 477 KB allocated,  92 B  copied, 6.0 MB peak memory
deep:           OK
409  μs ±  33 μs, 3.0 MB allocated, 870 B  copied, 6.0 MB peak memory
mtl (effectful)
shallow:        OK
36.4 μs ± 2.9 μs, 260 KB allocated,  71 B  copied, 6.0 MB peak memory
deep:           OK
36.9 μs ± 2.9 μs, 267 KB allocated, 179 B  copied, 6.0 MB peak memory
```
`filesize.1000`:
```
mtl (transformers)
shallow: OK
973  μs ±  87 μs, 7.2 MB allocated, 349 KB copied, 7.0 MB peak memory
deep:    OK
2.20 ms ± 175 μs,  15 MB allocated, 854 KB copied, 8.0 MB peak memory
mtl …
```

Benchmark mtl code run via transformers and effectful
